# constants exclusive for xml only
XML_HEADER = "ns2:item"
XML_PROJECT = "project"
XML_NAME = "name"
XML_PROJECTUID = "projectuid"
XML_STATUS = "status"
XML_BASIC = "basic"
XML_DIVISION = "division"
XML_SECTION = "section"
XML_GROUP = "group"
XML_DEPT = "department"
XML_CUSTOMER = "customer"
XML_DURATION = "duration"
XML_FULL = "full"
XML_PORTLET = "portlet"
XML_ROOT_PORTLET = "rootPortlet"
XML_MENU = "menu"
XML_ITEM = "item"
XML_MANAGER = "manager"
XML_USER = "user"
XML_EMAIL = "email"
XML_LAST_UPDATED = "lastupdated"
XML_BEGIN = "begin"
XML_END = "end"
XML_START = "start"
XML_REASON = "reason"
XML_PARAM = "param"
XML_PORTLET_ID = "portletID"
XML_MENU_ID = "menuID"
XML_ITEM_ID = "itemID"

# constants for json objects
OBJ_EMAIL_CONTENT_TYPE = "emailType"
OBJ_EMAIL_ALARM = "emailAlarm"
OBJ_EMAIL_REQUEST = "emailRequest"
OBJ_EMAIL_CONTENT = "content"
OBJ_EMAIL_BODY = "emailBody"
OBJ_EMAIL_ALARM_BODY = "emailAlarmBody"
OBJ_EMAIL_SUBJECT = "emailSubject"
OBJ_BASIC_INFO = "basic_info"
OBJ_DEV = "dev"
OBJ_SI = "si"
OBJ_NBP = "nbp"
OBJ_ID = "id"
OBJ_UID = "uid"
OBJ_NAME = "name"
OBJ_FULL_NAME = "fullname"
OBJ_TYPE = "type"
OBJ_VALUE = "value"
OBJ_VALUES = "values"
OBJ_GROUP = "group"
OBJ_VALUE_TEXT = "valuetext"
OBJ_FIRST_NAME = "firstname"
OBJ_LAST_NAME = "lastname"
OBJ_PASSWORD = "password"
OBJ_BUSOUKA_STATUS = "busoukaStatus"
OBJ_EMAIL_ADDR = "emailAddress"
OBJ_EMAIL_ADDR_DB = "emailaddr"
OBJ_WEATHER_INFO = "weather_info"
OBJ_USERNAME = "username"
OBJ_ONESIGN_UID = "onesign_uid"
OBJ_EXP = "exp"
OBJ_CODE = "code"
OBJ_STATUS = "status"
OBJ_WEATHER_SYMBOL = "wtherSymbol"
OBJ_IMPR_STATUS = "imprStatus"
OBJ_GRP_NAME = "grpName"
OBJ_MANAGER = "manager"
OBJ_PJMP_MAPPING = "pjmpmapping"
OBJ_PJ_DATA = "pjdata"
OBJ_PJ_TYPE = "pjType"
OBJ_DEV_DATA = "devImprovementData"
OBJ_SI_DATA = "siImprovementData"
OBJ_IMP_DATA = "improvementData"
OBJ_NO = "no"
OBJ_DIV_NO = "div_code"
OBJ_CONFIG = 'config'
OBJ_DEV_SUM = "devSummary"
OBJ_SI_SUM = "siSummary"
OBJ_BTI_SUM = "btiSummary"
OBJ_REF_COL = "reference_col"
OBJ_DEF_VALS = "defaultValues"
OBJ_FINALIZED_INFO = "finalizedInfo"
OBJ_DEV_SIT = "dev_proj_tool_situation"
OBJ_SI_SIT = "si_proj_tool_situation"
OBJ_COL_LABEL = "columnsLabel"
OBJ_SEI = 'SEI'
OBJ_MEI = 'MEI'
OBJ_SM_UID = "UID"
OBJ_EMAIL = 'email'
OBJ_ROLE = "role"
OBJ_IS_DELETED = "isDeleted"
OBJ_LAST_LOGIN = "last_login"
OBJ_ACCESS_TOKEN = "access_token"
OBJ_PROJECT_CODE = "projectCode"
OBJ_DIV_ABBR = "divisionAbbr"
OBJ_WITH_IMPR = "withImprovements"
OBJ_WITH_IMPR_COUNT = "withImprovementsCount"
OBJ_WITHO_IMPR = "woutImprovements"
OBJ_WITHO_IMPR_COUNT = "woutImprovementsCount"
OBJ_IMPR_RATE = "improvementRate"
OBJ_DEV_RATES = "dev_rates"
OBJ_REPORT_ID = "reportID"
OBJ_DEV_FHY = "dev_fhy"
OBJ_DEV_SHY = "dev_shy"
OBJ_SI_RATES = "si_rates"
OBJ_SI_FHY = "si_fhy"
OBJ_SI_SHY = "si_shy"
OBJ_ORG_DATA = "orgData"
OBJ_GROUP_DATA = "groupName"
OBJ_DIV_CODE = "divisionCode"
OBJ_B_NAME = "businessName"
OBJ_ABBR = "abbr"
OBJ_FULLNAME = "fullname"
OBJ_USER_SETTING = "user_settings"
OBJ_DEFAULT_PAGE = "default_page"
OBJ_SI_TYPE = "si_proj_list"
OBJ_DEV_TYPE = "dev_proj_list"
OBJ_TABLE_DATA = "tableData"
OBJ_FINALIZED = "finalized"
OBJ_DATE = "date"
OBJ_URL = "url"
OBJ_PERC = "percentage"
OBJ_NAME = "name"
OBJ_SUFFX = "suffixValues"
OBJ_TAB = "tab"
OBJ_INFO_FORMAT = "infoformat"
OBJ_ITEMS = "items"
OBJ_LABEL = "label"
OBJ_DATA_TYPE = "dataType"
OBJ_INPUT_TYPE = "inputType"
OBJ_OPTIONS = "options"
OBJ_DATA_SRC = "dataSrc"
OBJ_FILTER_BY = "filter_by"
OBJ_DB_COL = "dbColName"
OBJ_JSON_COL = "jsonColName"
OBJ_TABLE = "table"
OBJ_VALIDATION = "validation"
OBJ_REQUIRED = "required"
OBJ_MAX_LENGTH = "maxLength"
OBJ_RANGE = "range"
OBJ_MAX_WIDTH = "maxWidth"
OBJ_MAX = "max"
OBJ_MIN = "min"
OBJ_TABLE_HEADER = "tableHeader"
OBJ_TABLE_DATA = "tableData"
OBJ_TABLE_DATA_SMALL = "tabledata"
OBJ_REC_NO = "recno"
OBJ_COL_NO = "colno"
OBJ_BUSOUKA_DATA = "busoukadata"
OBJ_CANCEL_ALLOWED = "cancelAllowed"
OBJ_ALL = "全社"
OBJ_ALL_LABEL = "ALL"
OBJ_ALL_GROUPS = "全部門共通"
OBJ_ALL_GROUPS_LABEL = "ALLGROUP"
OBJ_ADD = "add"
OBJ_EDIT = "edit"
OBJ_DELETE = "delete"
OBJ_BUS_TARG_CODE = "busoukatargetcode"
OBJ_BUS_TARG_NAME = "busoukatargetname"
OBJ_BUS_DATA = "busoukadata"
OBJ_BUS_INFO_NAME = "busoukaInfoName"
OBJ_DATA_FORMULA = "dataFormula"
OBJ_DECIMAL_PLACE="decimalPlace"
OBJ_METHOD = "method"
OBJ_COLUMN = "column"
OBJ_EMAIL = "email"
OBJ_COUNT_COL = "count_column"
OBJ_TOTAL_COL = "total_column"
OBJ_BUSOUKA_FILENAME = "busoukafilename"
OBJ_BTI_DIVISION_ID = "divisionid"
OBJ_BTI_REPORT_ID = "reportid"
OBJ_LAST_UPDATED = "lastupdated"
OBJ_AUTO_SEND = "autosend"
OBJ_AUTO_SEND_ID = "autosend_id"
OBJ_AUTO_SEND_DATES = "autosend_dates"
OBJ_EMAIL_DEADLINE_DATE = "emailDeadlineDate"
OBJ_EMAIL_ALARM_DATE = "emailAlarmDate"
OBJ_EMAIL_REQUEST_DATE = "emailRequestDate"
OBJ_WEATHER_STATUS = "wtherSymbol"
OBJ_ICON = "icon"
OBJ_TEXT = "text"
OBJ_DEV_LABEL = "開発 DX推進"
OBJ_SI_LABEL = "SI DX推進"
OBJ_FILENAME = "filename"
OBJ_FILE = "file"
OBJ_FILE_URL = "file_url"
OBJ_FILE_UPLOADS = "file_uploads"
OBJ_DEL_UPLOADS = "delete_uploads"
OBJ_PROJ_CLASS = "pj_classification"
OBJ_EDITABLE = "isEditable"
OBJ_FORM_DATA_UPLOADS = "formdata_uploads"
OBJ_CONFIG_DATA = "configdata"
OBJ_DIV_TYPE = "div_type"
OBJ_DIV_NAME = "div_name"
OBJ_FY = "fiscal_year"

#Method in config
METHOD_COUNT_IF = "countif"
METHOD_SUM_IF = "sumif"
METHOD_SUM = "sum"
METHOD_AVE = "average"
METHOD_COUNT = "count"


# constants for menu item type
ITEM_PULLDOWN = "リスト"
ITEM_RADIO = "ラジオボタン"
ITEM_CHECK = "チェックボックス"
ITEM_TEXT = "テキスト（文字列、数値、エリア）"
ITEM_TYPO_TEXT = "???キスト（文字列、数値、エリア）"

# constants for value texts
VAL_PLEASE_SELECT = "ご選択ください"
VAL_NOT_ENTERED = "未入力"
VAL_EMPTY = ""
VAL_NONE = None

# constants for request
REQ_MODULE_IDENTIFIER = "module_identifier"
REQ_ACTION_IDENTIFIER = "action_identifier"
REQ_HEADER = "header"
REQ_BODY = "body"
REQ_DATA = "data"
REQ_METHOD = "method"
REQ_RESPONSE_DETAILS = "response_details"
HTTP_SM_ATTR_QUERY = "HTTP_SM_ATTR_QUERY"
HTTP_AUTHORIZATION = "HTTP_AUTHORIZATION"
REQ_TOKEN = "token"

# constants for response
RESP_HEADER = "header"
RESP_BODY = "body"
RESP_DATA = "data"
RESP_RESPONSE_DETAILS = "response_details"
RESP_ERRORS = "errors"

# constants for ID
ID_REFERENCE = "reference_id"
ID_USER = "user_id"
ID_MESSAGE = "message_id"
ID_REPORT = "reportId"
ID_DIVISON = "divisionId"
ID_GROUP = "groupId"
ID_ROLE = "roleid"
ID_SSO = "ssoid"
ID_COL = "colId"


# constant for labels
CRITERIA = "criteria"
HTTP_STATUS = "http_status"
HTML_DATA = "html_data"
DATE_UPDATED = "date_updated"
UPDATED_BY = "updated_by"
EXIT_CODE = "exit_code"
TOKEN = "token"
INSTANCES = "instances"
SERIALIZED = "serialized"
SPACE = " "
WEATHER = "weather"
FIRST_Q = "１Ｑ自動化予定"
SECOND_Q = "２Ｑ自動化予定"
THIRD_Q = "３Ｑ自動化予定"
FOURTH_Q = "４Ｑ自動化予定"
SI_FIRST_Q = "１Ｑ適用予定"
SI_SECOND_Q = "２Ｑ適用予定"
SI_THIRD_Q = "３Ｑ適用予定"
SI_FOURTH_Q = "４Ｑ適用予定"
SUNNY = "sunny"
CLOUDY = "cloudy"
RAINY = "rainy"
IDX_ZERO = "0"
IDX_ONE = "1"
IDX_TWO = "2"
DEFAULT_STATUS = 3
DASH = "-"
STATUS = "status"
DETAILS = "details"
STATUS_CODE = "status_code"
NO_SELECTION = "未選択"
PLEASE_SELECT = "ご選択ください"
NEXTYEAR = "来年度予定"
N_A = "対象外"
CUT_OFF = "削除"
DONE = "自動化対応済"
ASIBO = "ASIBO適用済"
APPLIED = "ツール適用済"
NOT_ENTERED = "予定未入力"
EMPTY = "empty"
DEV_FHY_KYEN = "DEV_FHY_ECO_BENEFIT"
DEV_SHY_KYEN = "DEV_SHY_ECO_BENEFIT"
SI_FHY_KYEN = "SI_FHY_ECO_BENEFIT"
SI_SHY_KYEN = "SI_SHY_ECO_BENEFIT"
STRICT = "strict"
COL_LABELS = "columnsLabels"
SUMMARY = "summary"
INCREMENT = "increment"
DECREMENT = "decrement"
DAILY = "daily"
MONTHLY = "monthly"
PARENT = "parent"
DELIMITER = ":"
NON_BUSOUKA_KJ = "DX推進対象外"
UNSELECTED_KJ = "DX推進状況未選択"
UNDERSCORE = "_"
CONF = "conf"
LASTUPDATED = "lastupdated"
LOCK = "lock"
RELEASE = "release"
FIRST_HALF_FY = "1st_half_FY"
SECOND_HALF_FY = "2nd_half_FY"
ACTUAL = "actual"
DATA = "data"
SOURCE = "source"
BTI = "bti"
REPORT_IDS = "report_ids"
LABELS = "labels"
DISPLAY = "display"
PROSPECT = "prospect"
TARGET = "target"
DEV_DIV = "dev_divisions"
SI_DIV = "si_divisions"
BTI_DIV = "bti_divisions"
REPORT_ID = "report_id"

RATE = "rate"
TRUE = True
FALSE = False

# SI portlet type
SI_PORTLET_TYPE = "9"

# BTI LABELS
BTI_TOOLS_SHTK = "Tools Suiheitenkai Information"
BTI_INVEST = "Busouka Investment Situation"
BTI_WORK = "work_system_reform"

# DB model constants
DB_ORG = "organization"

# Log params
LOG_SSO = "sso_id"
LOG_C_F = "comp_code"
LOG_C_CODE = "c_f_name"

# Email constants
EMAIL_FROM = "From"
EMAIL_TO = "To"
EMAIL_BCC = "Bcc"
EMAIL_CC = "Cc"
EMAIL_SUBJECT = "Subject"

# For resource keys
RESOURCE_KEY_BTI = "bti"
RESOURCE_KEY_COMPANY_WIDE = "company_wide"
RESOURCE_KEY_CORE = "core"
RESOURCE_KEY_CRON = "cron"
RESOURCE_KEY_DIVISION = "division"
RESOURCE_KEY_INFO = "info"
RESOURCE_KEY_KPI = "kpi"
RESOURCE_KEY_PJMP = "pjmp"
RESOURCE_KEY_PROJECT_DATA = "project_info"
RESOURCE_KEY_USER = "user"
RESOURCE_KEY_ORG = "org_management"


# HTTP CODES
HTTP_500 = 500
HTTP_403 = 403
HTTP_401 = 401
HTTP_400 = 400
HTTP_200 = 200
# FILE UPLOAD
TEMP_FILE = "temp_file"

# ERROR DETAILS
ERR = "error"
ERR_TIMESTMP = "timestamp"
ERR_VERSION = "version"
ERR_CODE = "code"
ERR_MSG_ID = "message_id"
ERR_MSG = "message"
ERR_DETAIL = "detail"
ERR_PATH = "path"

ARG_BP = "bp"
ARG_NBP = "nbp"
ARG_BOTH = "both"
ARG_FILE = "_file_lock"


# TABLE STATE
STATE_OPERATION_ID = "operation_id"
STATE_DIV_GROUP_ID = "div_group_id"
STATE_LAST_UPDATED = "last_updated"
STATE_LOCKED = "locked"

# PROJECT INTRODUCTION RATE
HUNDRED_FLOAT = 100.0

JSON_FILE_EXT = '.json'

OBJ_FORMAT = 'format'
OBJ_AUTO_ON_UPDATE = 'auto_on_update'
OBJ_NO_INPUT = 'no_input'

# TOTAL EFFECT
APRIL_IDX = 4
SEPTEMBER_IDX = 9
FY_MONTHS_COUNT = 6
REPORT_ID_COLNAME = "report_id"
SUMMARY_COLNAME = "summary"
DIVISION_CODE_LEN = 4
DIVISION_ID='div_id'

# PHASE 5 REQUIREMENT 5
FHY_KYEN_KNJ = "上期効果額"
SHY_KYEN_KNJ = "下期効果額"
MONTH_KNJ = "月"
START_MONTH = 4
END_MONTH = 3
NO_MONTHS = 12
UNIT = "unit"
TITLE = "title"

# PHASE 6
ADMIN = "admin"
SYSTEM = "システム"
FHY = "fhy"
CONCLUSION = "conclusion"
EXPIRES_AT = "expires_at"
CREATED_AT = "created_at"
OBJ_MAX_TOTAL_EFFECT_EDIT_SESSION = "max_lock_session"
OBJ_TOTAL_EFFECT_EDIT_TIME_LEFT_REMINDER = "time_left_reminder"
FORCE_EXPIRED_BY = "force_expired_by"
REMAINING_TIME = "remaining_time"

# PHASE 7 
OBJ_PROJECT_MANAGER_NAME = "projectManager"
OBJ_PROJECT_MANAGER_EMAIL = "projectManagerEmail"