# Generated by Django 4.1.7 on 2023-03-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('homes', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeUserAccess',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homes.homes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
            options={
                'db_table': 'HomeUserAccess',
                'managed': True,
            },
        ),
    ]
