# Generated by Django 4.1.7 on 2023-04-17 02:31

import core.util.model_to_dict
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=200, null=True)),
                ('role', models.IntegerField()),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
            bases=(models.Model, core.util.model_to_dict.ModelToDictionary),
        ),
    ]
