# Generated by Django 4.1.7 on 2023-03-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.EmailField(max_length=200, unique=True)),
                ('role', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'User',
                'managed': True,
            },
        ),
    ]
