# Generated by Django 4.1.7 on 2023-03-24 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=100)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homes.homes')),
            ],
            options={
                'db_table': 'devices',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='devices.devices')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homes.rooms')),
            ],
            options={
                'db_table': 'channels',
                'managed': True,
            },
        ),
    ]
