# Generated by Django 4.1.7 on 2023-05-02 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.rooms'),
        ),
        migrations.AddField(
            model_name='devices',
            name='status',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='devices',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='home',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homes.homes'),
        ),
    ]
