# Generated by Django 4.1.7 on 2023-05-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devices_room_devices_status_devices_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.JSONField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='devices',
            name='type',
            field=models.CharField(choices=[('MNTR', 'Monitor'), ('CTRL', 'Control'), ('SECU', 'Security')], max_length=100, null=True),
        ),
    ]
