# Generated by Django 4.1.7 on 2023-05-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_alter_devices_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='channels',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
