# Generated by Django 4.1.7 on 2023-05-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_channels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
