# Generated by Django 4.1.7 on 2023-03-24 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Homes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='homes.homes')),
            ],
            options={
                'db_table': 'Rooms',
                'managed': True,
            },
        ),
    ]
